filebeat.inputs:
- type: filestream
  id: openemr-audit-logs
  paths:
    - /var/log/mariadb/mariadb_audit.log
  fields:
    service: mariadb
    log_type: audit

- type: filestream
  id: openemr-app-logs
  paths:
    - /var/log/openemr/*.log
  fields:
    service: openemr_app

- type: filestream
  id: openemr-web-access
  paths:
    - /var/log/openemr/apache2/access.log
  fields:
    service: openemr_app
    log_type: web_access

processors:
  - if:
      equals:
        fields.log_type: web_access
    then:
      - dissect:
          tokenizer: '%{source.ip} - - [%{apache.access.time}] "%{http.request.method} %{url.original} HTTP/%{http.version}" %{http.response.status_code|long} %{http.response.body.bytes|long} "%{http.request.referrer}" "%{user_agent.original}"'
          field: message
          target_prefix: ""
          ignore_failure: true
      - timestamp:
          field: apache.access.time
          layouts:
            - '02/Jan/2006:15:04:05 -0700'
          ignore_failure: true
      - drop_fields:
          fields: ["apache.access.time"]
          ignore_missing: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "${ELASTICSEARCH_USERNAME:elastic}"
  password: "${ELASTICSEARCH_PASSWORD}"
  pipeline: "filebeat-web-geoip"

#output.console:
#  pretty: true
  